version: '3.8'  
services:   
  backend:     
    build: .     
    container_name: skillmatch-backend     
    ports:       
      - "3000:3000"     
    environment:       
      - NODE_ENV=production       
      - DB_HOST=host.docker.internal       
      - DB_PORT=5432       
      - DB_NAME=skillMatch       
      - DB_USER=postgres       
      - DB_PASS=kali     # Changed from DB_PASSWORD to DB_PASS
    extra_hosts:       
      - "host.docker.internal:host-gateway"     
    restart: unless-stopped